# Generated by Django 3.1.5 on 2021-01-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('signature', models.CharField(blank=True, max_length=128, null=True, verbose_name='签名')),
                ('avatar', models.ImageField(default='static/image/default.jpg', upload_to='static/image/', verbose_name='用户图像')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='博客正文')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='博客标签')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('read_count', models.IntegerField(verbose_name='阅读量')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.account')),
            ],
        ),
    ]
