# Generated by Django 3.1.5 on 2021-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='标签名称'),
        ),
    ]
