# Generated by Django 3.1.5 on 2021-01-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art', to='articles.account'),
        ),
    ]
